x=27
y=15
sum = x + y
subtraction = x - y
multiplication = x * y
division = x / y
print(f"{x}+{y}={sum}")
print(f"{x}-{y}={subtraction}")
print(f"{x}*{y}={multiplication}")
print(f"{x}/{y}={division}")
